name: CI

on:
  release:
    types: [created]
  push:
    branches: [ "main" ]

permissions: write-all

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install tools
        run: sudo apt update && sudo apt install -y build-essential unzip jq
      - name: Build
        run: ./build.sh
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: /opt/make-4.4-ohos-arm64.tar.gz
      - name: upload release asset
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }} 
          asset_path: /opt/make-4.4-ohos-arm64.tar.gz
          asset_name: make-4.4-ohos-arm64.tar.gz
          asset_content_type: application/octet-stream 
